language: ruby
rvm:
  - 2.3.4

before_cache:
  - echo "before_cache"

before_install:
  - 'REDPEN_URL="https://github.com/redpen-cc/redpen/releases/download"'
  - 'REDPEN_VERSION="1.10.1"'
  - 'DIR_CACHE="${HOME}/custom_cache"'

install:
  - 'curl --request GET --location --continue-at - --create-dirs --output "${DIR_CACHE}/redpen-${REDPEN_VERSION}.tar.gz" "${REDPEN_URL}/redpen-${REDPEN_VERSION}/redpen-${REDPEN_VERSION}.tar.gz"'
  - 'cd ${DIR_CACHE} && tar xvf "./redpen-${REDPEN_VERSION}.tar.gz" && cd -'
  - 'export PATH="$PATH:${DIR_CACHE}/redpen-distribution-${REDPEN_VERSION}/bin"'
  - 'gem install asciidoctor'
  - 'pip install --user pyaml'
  - 'pip install --user docopt'

script:
  - ./build/release.sh

cache:
  directories:
    - ${DIR_CACHE}

branches:
  except:
    - /^\d+\.\d+(\.\d+)?(-\S*)?$/
