language: ruby
rvm:
  - 2.3.4

sudo: required
services:
  - docker

env:
  - DOCKER_COMPOSE_VERSION=1.17.0

cache:
  directories:
    - $HOME/.m2
    - node_modules

addons:
  apt:
    packages:
      - docker-ce
      - caca-utils # img2txt

before_install:
  - npm install -g conventional-changelog-cli
  - /home/travis/.nvm/versions/node/v8.9.1/bin/conventional-changelog-cli -p angular -i CHANGELOG.md -s -r 0
  - cat CHANGELOG.md
  - sudo rm /usr/local/bin/docker-compose
  - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin

script:
  - sudo docker-compose -f sample_screenTestProj/docker-compose.yml build
  - sudo docker-compose -f sample_screenTestProj/docker-compose.yml up -d
    #  - (cd sample_screenTestProj && ./build.sh && ./run-cuke.sh && cd ..) 
  - sudo docker-compose -f sample_screenTestProj/docker-compose.yml down
    #  - find sample_screenTestProj/build/reports/ -name '*.png'|sort|xargs -I{} sh -c 'echo;echo {}; img2txt -W 60 -f ansi "{}"'

after_success:
  - ./build/release.sh

branches:
  except:
    - /^\d+\.\d+(\.\d+)?(-\S*)?$/
