language: ruby
rvm:
  - 2.3.4

sudo: required
services:
  - docker

env:
  - DOCKER_COMPOSE_VERSION=1.17.0

cache:
  directories:
    - $HOME/.m2
    - $HOME/.rvm

addons:
  apt:
    packages:
      - docker-ce
      - caca-utils # img2txt

before_install:
  - npm install -g conventional-changelog-cli
  - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose

script:
  - ./docker-compose -f sample_screenTestProj/docker-compose.yml build
  - ./docker-compose -f sample_screenTestProj/docker-compose.yml up -d
  - (cd sample_screenTestProj && ./build.sh && ./run-cuke.sh && cd ..) 
  - ./docker-compose -f sample_screenTestProj/docker-compose.yml down
  - find sample_screenTestProj/build/reports/ -name '*.png'|sort|xargs -I{} sh -c 'echo;echo {}; img2txt -W 60 -f ansi "{}"'

after_success:
  - conventional-changelog -r 5 # すべてのcommit表示
  - conventional-changelog -p angular -i CHANGELOG.md -s -r 5 # angularルールでの直近５リリースのchangelog
  - cat CHANGELOG.md
  - ./build/release.sh

branches:
  except:
    - /^\d+\.\d+(\.\d+)?(-\S*)?$/

